version: '3.8'

services:
  config-server:
    image: config-server:latest
    networks:
      - airkerala
    ports:
      - "8081:8080"

  eureka-server:
    image: eureka-server:latest
    networks:
      - airkerala
    ports:
      - "8082:8080"

  api-gateway:
    image: api-gateway:latest
    networks:
      - airkerala
    ports:
      - "8083:8080"

  booking-confirmation:
    image: booking-confirmation:latest
    networks:
      - airkerala
    ports:
      - "8086:8086"

  airkerala-booking-app:
    image: airkerala-booking-app:latest
    networks:
      - airkerala
    ports:
      - "8085:8085"

  loginapp:
    image: loginapp:latest
    networks:
      - airkerala
    ports:
      - "8087:8080"

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: akhil@123
      MYSQL_DATABASE: airkerala
    ports:
      - "3306:3306"
    networks:
      - airkerala
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  airkerala:
    external: true

volumes:
  mysql_data:
